<!-- 

latur home town 
-->

<HTML>
<HEAD><TITLE>
  <CENTER>My CITY</CENTER>
  </TITLE>
  </HEAD>
<BODY BGCOLOR="lavender">
<BODY BGCOLOR="lavender">
<FONT SIZE="7" FACE="ARIAL" COLOR="BLUE"><CENTER>Nanded ,
<SMALL>MAHARASHTRA</SMALL></FONT><BR>
<BODY BGCOLOR="RED"><CENTER>
<font size="4" face="arial" color="pink"<B>Landmarks</B></font><BR>
<font size="4" face="arial" color="Black"<B> Hazur Sahib Nanded railway station    </B></font><BR>
<font size="4" face="arial" color="red"<B>FAMOUS Place of Nanded </B></font><BR> Takhat Sachkhand Shri Hazur Abchalnagar Sahib Gurudwara
<font size="4" face="arial" color="blue"<B>  </B></font><BR>
<BODY BGCOLOR="PINK"<CENTER>
<MARQUEE BEHAVIOUR="SLIDE"> Wonderful Place To Visit</MARQUEE>
<MARQUEE BEHAVIOUR="SLIDE">Nanded Is best City for Education</MARQUEE>
<IMG SRC="  https://i.imgur.com/SJd8c3m.jpg   " WIDTH="400" HEIGHT="400" ALT="IMAGE CANNOT BE DISPLAYED">
<p> Nanded is a city in Maharashtra state,India,<br> 
and is one of the largest cities of the Marathwada region.<br> 
<br> 
The city is a tourist hub surrounded by many historical monument,<br>
including Udgir Fort and Kharosa Caves.and <br>
The people in Nanded are called Nandedkar.<br>
The most spoken language in Nanded is Marathi.<br>
The city's quality of education attracts students from all over Maharashtra.<br>
Takhat Sachkhand Shri Hazur Abchalnagar Sahib is the main Gurudwara of Nanded, it is the 2 largest Gurudwara after amritsar.and is one of the five High seats of Authority of the sikhs. This is the place where Shri GuruGobind Singhji breathed his last. The Gurudwara is situated in Nanded Town.<br>
</p> 
<h1>Education And Research</h1>
<p> Nanded has developed into an educational hub for secondary,<br>
higher secondary, and university education.<br>
The district is known in Maharashtra for its "Nanded Pattern" of study,<br>
which involves intensive coaching given in the city.<br>
Students of junior colleges in Nanded have a good record in<br>
taking competitive engineering and medical entrance exams.</p>
<h2>Thanks For MY Home Town Watching Website <h2>
</BODY>

</HTML>
